version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Greeting
          command: |
            cat /etc/lsb-release
      - run:
          name: Print the Current Time
          command: ./minikube-start.sh
workflows:
  version: 2
  build_and_test:
    jobs:
      - e2e_approval:
          type: approval
      - build:
          requires:
            - e2e_approval
